
[[pages]]
path = "src/interface/usability_evaluation.py"
name = "Usability Evaluation"
icon = "ğŸ‘¤"

[[pages]]
path = "src/interface/correctness_evaluation.py"
name = "Corretness Evaluation"
icon = "ğŸ¯"
