
[[pages]]
path = "src/interface/usability_evaluation.py"
name = "Usability Evaluation"
icon = ""

[[pages]]
path = "src/interface/correctness_evaluation.py"
name = "Corretness Evaluation"
icon = ""

[[pages]]
path = "src/interface/compare_full_answers.py"
name = "Compare All Models"
icon = ""

[[pages]]
path = "src/interface/compare_knowledge_bases.py"
name = "Compare Knowledge Bases"
icon = ""


